survos_crawler:
# if you've run symfony proxy:domain:attach my-project, then the error messages will be displayed with this prefix.  That way, you can simply click on a link to open the page.
    base_url: 'https://easyadmin-cast.wip/'
    user_class: App\Entity\User
    users:
        - admin@example.com
        - moderatoradmin@example.com
        - superadmin@example.com
        - tisha@symfonycasts.com
    max_depth : 3
    # max per route per user
    max_per_route: 2
    routes_to_ignore :
        - 'app_logout'
