<?php

namespace App\Tests\Crawl;

use PHPUnit\Framework\Attributes\TestDox;
use PHPUnit\Framework\Attributes\TestWith;
use Survos\CrawlerBundle\Tests\BaseVisitLinksTest;
use Symfony\Bundle\FrameworkBundle\KernelBrowser;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class CrawlAsAdminTest extends BaseVisitLinksTest
{
	#[TestDox('/$method $url ($route)')]
	#[TestWith(['admin@example.com', 'App\Entity\User', '/', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', '/admin', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', '/profile/show', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', '/questions/heads-below-a-loud-crash-now-who-did', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', '/questions/alice-was-not-going-to-begin-with-and-being-so', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', '/questions/queen-will-hear-you-you-see-she-came-upon-a', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/topic', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/user', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', '/questions/queens-hedgehog-just-now-only-it-ran-away-when', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', '/questions/nile-on-every-golden-scale-how-cheerfully-he', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', '/questions/bill-the-lizard-could-not-join-the-dance-will', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', '/questions/mystery-the-mock-turtle-angrily-really-you', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/new', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/batch-delete', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer?page=1&sort%5Bid%5D=ASC', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer?page=1&sort%5Banswer%5D=DESC', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer?page=1&sort%5Bvotes%5D=DESC', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer?page=1&sort%5BansweredBy%5D=DESC', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer?page=1&sort%5BcreatedAt%5D=DESC', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/user/29', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/800', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/800/edit', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/800/delete', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/user/30', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/799', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/799/edit', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/799/delete', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/798', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/798/edit', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/798/delete', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/797', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/797/edit', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/797/delete', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/user/32', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/796', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/796/edit', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/796/delete', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/795', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/795/edit', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/795/delete', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/user/31', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/794', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/794/edit', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/794/delete', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/793', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/793/edit', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/793/delete', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/792', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/792/edit', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/792/delete', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/791', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/791/edit', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/791/delete', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/790', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/790/edit', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/790/delete', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/789', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/789/edit', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/789/delete', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/788', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/788/edit', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/788/delete', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/787', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/787/edit', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/787/delete', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/786', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/786/edit', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/786/delete', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/785', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/785/edit', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/785/delete', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/784', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/784/edit', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/784/delete', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/783', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/783/edit', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/783/delete', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/782', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/782/edit', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/782/delete', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/781', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/781/edit', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer/781/delete', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer?page=1', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer?page=2', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer?page=3', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer?page=4', 200])]
	#[TestWith(['admin@example.com', 'App\Entity\User', 'admin/answer?page=5', 200])]
	public function testRoute(string $username, string $userClassName, string $url, string|int|null $expected): void
	{
		parent::testWithLogin($username, $userClassName, $url, (int)$expected);
	}
}
